spring:
  datasource:
    url: jdbc:h2:mem:users3
    username: iarlen
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
 
  data:
    redis:  
      host: 127.0.0.1
      port: 6379
      

  resilient4j.circuitbreaker:
    instances:
      statisticsCB:
        minimumNumberOfCalls: 4
        slidingWindowSize: 8
